name: Setup and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract ZIP file
        run: bash extract_and_setup.sh

      - name: Install dependencies and run tests
        run: bash test_application.sh

      - name: Deploy application
        run: bash deploy_application.sh
